version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-browsers-legacy

    working_directory: ~/repo
    
    environment:
      MAVEN_OPTS: -Xmx3200m
      
    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
            
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
          
      # run tests!
      - run: mvn integration-test
